name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: docker build -f Dockerfile.qemu -t armv8-neon-explorer-qemu .
    
    - name: Build project
      run: docker run --rm -v ${{ github.workspace }}:/workspace armv8-neon-explorer-qemu make all
    
    - name: Run tests
      run: docker run --rm -v ${{ github.workspace }}:/workspace armv8-neon-explorer-qemu make test

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install clang-format
      run: sudo apt-get install -y clang-format
    
    - name: Check code formatting
      run: find src include examples tests -name "*.c" -o -name "*.h" | xargs clang-format --style=file --Werror --dry-run
